language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - mvn clean install -Pqulice --errors --batch-mode
  - mvn clean
  - pdd --source=$(pwd) --file=/dev/null
  - est --dir=est --file=/dev/null
before_install:
  - rvm install 2.6.0
  - rvm use 2.6.0
install:
  - gem install pdd -v 0.20.5
  - gem install est -v 0.3.4
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - oraclejdk8
  - openjdk7
