version: {build}
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
before_build:
  - cmd: java -version
  - cmd: choco install maven
  - cmd: mvn -version
test_script:
  - cmd: mvn clean install -Pqulice

